"use client";

import React, { useState, useEffect, useRef } from "react";
import QRCode from "qrcode";

interface PrintQueueTicketProps {
  queueNumber: string;
  residentName?: string;
  serviceName: string;
  appointmentDate: string | Date;
  appointmentSlot: string;
  isPriority?: boolean;
  department?: string;
  dateGenerated?: string | Date;
  branding?: any;
  themeColor?: string;
  triggerPrint?: boolean;
  onPrintCompleted?: () => void;
  paperWidth?: "58mm" | "80mm";
}

const formatDate = (dateStrOrObj: string | Date | null | undefined): string => {
  if (!dateStrOrObj) return "N/A";
  const date = new Date(dateStrOrObj);
  if (isNaN(date.getTime())) return String(dateStrOrObj);
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const y = date.getFullYear();
  return `${m}/${d}/${y}`;
};

const formatDateTime = (dateStrOrObj: string | Date | null | undefined): string => {
  if (!dateStrOrObj) return "N/A";
  const date = new Date(dateStrOrObj);
  if (isNaN(date.getTime())) return String(dateStrOrObj);
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const y = date.getFullYear();

  let hours = date.getHours();
  const minutes = String(date.getMinutes()).padStart(2, "0");
  const seconds = String(date.getSeconds()).padStart(2, "0");
  const ampm = hours >= 12 ? "PM" : "AM";
  hours = hours % 12;
  hours = hours ? hours : 12;
  const h = String(hours).padStart(2, "0");

  return `${m}/${d}/${y} ${h}:${minutes}:${seconds} ${ampm}`;
};

const parseQueueNumber = (num: string) => {
  if (!num) return { date: "", shift: "", code: "N/A", isFormatted: false };
  const parts = num.split('-');
  // Standard format generated by generateQueueNumber: MMDDYYYY-SHIFT-PREFIXSEQUENCE (e.g., 07072026-AM-T001)
  if (parts.length === 3) {
    const dateStr = parts[0];
    let formattedDate = dateStr;
    if (dateStr.length === 8) {
      formattedDate = `${dateStr.substring(0, 2)}/${dateStr.substring(2, 4)}/${dateStr.substring(4)}`;
    }
    return {
      date: formattedDate,
      shift: parts[1],
      code: parts[2],
      isFormatted: true
    };
  }
  return {
    date: "",
    shift: "",
    code: num,
    isFormatted: false
  };
};

export default function PrintQueueTicket({
  queueNumber,
  serviceName,
  appointmentDate,
  appointmentSlot,
  dateGenerated = new Date(),
  branding,
  triggerPrint = false,
  onPrintCompleted,
}: PrintQueueTicketProps) {
  const iframeRef = useRef<HTMLIFrameElement | null>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string>("");

  useEffect(() => {
    if (!queueNumber) return;
    QRCode.toDataURL(queueNumber, {
      width: 200,
      margin: 1,
      color: { dark: "#000000", light: "#ffffff" },
    })
      .then((url) => setQrDataUrl(url))
      .catch((err) => console.error("QR generation error:", err));
  }, [queueNumber]);

  useEffect(() => {
    if (!triggerPrint || !qrDataUrl) return;

    const iframe = iframeRef.current;
    if (!iframe) return;

    const ticketHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8" />
          <title>Queue Ticket</title>
          <style>
            @page {
              size: 80mm auto;
              margin: 0mm !important;
            }
            * {
              box-sizing: border-box;
              margin: 0;
              padding: 0;
            }
            body {
              width: 70mm;
              margin: 0;
              padding: 2mm 1mm 2mm 0mm;
              font-family: monospace, Courier, sans-serif;
              color: #000;
              background: #fff;
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
            }
            .ticket-card {
              width: 68mm;
              border: 2px solid #000;
              border-radius: 8px;
              padding: 8px 6px;
              text-align: center;
              font-weight: 900;
            }
            .header-logo {
              width: 36px;
              height: 36px;
              filter: grayscale(1) contrast(1.2);
              margin-bottom: 4px;
            }
            .country-title {
              font-size: 7px;
              letter-spacing: 0.5px;
              text-transform: uppercase;
            }
            .muni-title {
              font-size: 9px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              margin-top: 1px;
            }
            .prov-title {
              font-size: 6.5px;
              letter-spacing: 0.5px;
            }
            .dotted-sep {
              border-top: 1.5px dotted #000;
              margin: 4px 0;
            }
            .queue-box {
              border: 1.5px dashed #000;
              padding: 6px 4px;
              border-radius: 6px;
              background: #fcfcfc;
              margin-top: 2px;
            }
            .queue-num {
              font-size: 22px;
              font-weight: 900;
              letter-spacing: 0.5px;
              display: block;
            }
            .details {
              font-size: 8.5px;
              text-align: left;
              display: flex;
              flex-direction: column;
              gap: 3px;
              margin: 4px 0;
            }
            .row {
              display: flex;
              justify-content: space-between;
              border-bottom: 1px dotted #000;
              padding-bottom: 2px;
            }
            .qr-img {
              width: 80px;
              height: 80px;
              border: 1px solid #000;
              padding: 3px;
              border-radius: 3px;
            }
          </style>
        </head>
        <body>
          <div class="ticket-card">
            ${branding?.logo ? `<img src="${branding.logo}" class="header-logo" alt="Seal" />` : ""}
            <div class="muni-title">Local Government Unit</div>

            <div class="dotted-sep"></div>

            <span style="font-size: 8px; text-transform: uppercase; letter-spacing: 1px;">Queue Ticket Number</span>
            <div class="queue-box">
              <span class="queue-num">${queueNumber}</span>
            </div>

            <div class="dotted-sep"></div>

            <div class="details">
              <div class="row"><span>Service:</span><span style="text-align: right; max-width: 65%;">${serviceName}</span></div>
              <div class="row"><span>Date:</span><span>${formatDate(appointmentDate)}</span></div>
              <div class="row"><span>Schedule:</span><span>${appointmentSlot}</span></div>
              <div style="display: flex; justify-content: space-between; padding-top: 1px;">
                <span>Created:</span><span>${formatDateTime(dateGenerated)}</span>
              </div>
            </div>

            <div class="dotted-sep"></div>

            <div style="display: flex; flex-direction: column; align-items: center; gap: 3px; margin-top: 2px;">
              <img src="${qrDataUrl}" class="qr-img" alt="QR" />
              <span style="font-size: 6.5px; text-transform: uppercase; letter-spacing: 0.5px;">Scan QR Code at Counter</span>
            </div>
          </div>
        </body>
      </html>
    `;

    const doc = iframe.contentWindow?.document || iframe.contentDocument;
    if (doc) {
      doc.open();
      doc.write(ticketHtml);
      doc.close();

      // Trigger print smoothly without stealing window focus
      const timer = setTimeout(() => {
        try {
          iframe.contentWindow?.print();
        } catch (e) {
          console.error("Iframe printing error:", e);
        } finally {
          setTimeout(() => {
            if (onPrintCompleted) onPrintCompleted();
          }, 800);
        }
      }, 50);

      return () => clearTimeout(timer);
    }
  }, [triggerPrint, qrDataUrl, queueNumber, serviceName, appointmentDate, appointmentSlot, dateGenerated, branding, onPrintCompleted]);

  return (
    <iframe
      ref={iframeRef}
      style={{
        position: "fixed",
        top: "-9999px",
        left: "-9999px",
        width: "80mm",
        height: "150mm",
        border: "none",
        visibility: "hidden",
        pointerEvents: "none",
      }}
      title="Silent Ticket Printer"
    />
  );
}
